---
timeout: 3600s
steps:
  - id: prepare
    name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
    entrypoint: /bin/bash
    args:
      - "-e"
      - "-x"
      - "-c"
      - >- # folded text - replace newlines with spaces - each command needs to be separated by ';'
        gcloud projects create ${_TEST_PROJECT_ID} --folder ${_FOLDER_ID} ;
        sleep 10 ;
        trap "gcloud projects delete ${_TEST_PROJECT_ID} --quiet " ERR ;
        gcloud billing projects link ${_TEST_PROJECT_ID} --billing-account=${_BILLING_ACCOUNT} ;

  - id: pre_tf_setup
    name: "${_BUILDER_IMAGE_NAME}:${_BUILDER_IMAGE_TAG}"
    entrypoint: /bin/bash
    