---
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_TAG}', '.']

images: ['${_IMAGE_TAG}']
substitutions:
  _IMAGE_TAG: '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/ci/builder:latest'
options:
  dynamicSubstitutions: true
